#!/bin/bash

cat <<EOT >> /etc/httpd/conf.d/elasticbeanstalk/custom.conf
<Directory /var/www/html>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
EOT

# Restart Apache
sudo service httpd restart
